---
# file: roles/common/defaults/main.yml
proxy_env:
  no_proxy: '*'
#  http_proxy: http://172.16.111.1:8080
#  https_proxy: http://172.16.111.1:8080
#rhel_subscription:
#  username: 'username'
#  password: 'password'
#ntp_server: 172.16.111.1
grub_cfg_uefi: "/boot/efi/EFI/{{ ansible_distribution|lower }}/grub.cfg"
grub_cfg_legacy: "/boot/grub2/grub.cfg"
kdump_partition: "/dump"
generate_host: False
kdump_path: "/var/crash"
#common_user:
#  # user/password="hidepin/hidepin123"
#  - { name: 'hidepin', password: '$1$SomeSalt$buSRLdQkj4QgWzx.tbjqv1', uid: '1000', group: 'hidepin', gid: '1000' }
limits_setting:
  - { domain: 'root', type: 'soft', item: 'nofile', value: '65536' }
  - { domain: 'root', type: 'hard', item: 'nofile', value: '65536' }
#  - { domain: 'tomcat8', type: 'soft', item: 'nofile', value: '65536' }
#  - { domain: 'tomcat8', type: 'hard', item: 'nofile', value: '65536' }
#  - { domain: 'tomcat8', type: 'soft', item: 'nproc', value: '8192' }
#  - { domain: 'tomcat8', type: 'hard', item: 'nproc', value: '8192' }
#  - { domain: 'jboss6', type: 'soft', item: 'nofile', value: '65536' }
#  - { domain: 'jboss6', type: 'hard', item: 'nofile', value: '65536' }
#  - { domain: 'jboss6', type: 'soft', item: 'nproc', value: '8192' }
#  - { domain: 'jboss6', type: 'hard', item: 'nproc', value: '8192' }
#  - { domain: 'postgres', type: 'soft', item: 'nofile', value: '65536' }
#  - { domain: 'postgres', type: 'hard', item: 'nofile', value: '65536' }
tuned_profile: 'default'
tuned_profile_parameter:
  - section: 'main'
    parameter:
      - { option: 'include', value: 'throughput-performance' }
  - section: 'sysctl'
    parameter:
      - { option: 'net.ipv4.ip_local_port_range', value: '32768 64999' }
      - { option: 'net.core.somaxconn', value: '511' }
      - { option: 'net.ipv4.tcp_keepalive_intvl', value: '5' }
      - { option: 'net.ipv4.tcp_keepalive_probes', value: '5' }
      - { option: 'net.ipv4.tcp_keepalive_time', value: '60' }
kernel_update: True
update_pkg:
#  - glibc
#  - glibc-common
#  - glibc-devel
#  - glibc-headers
#  - systemd
